---
- name: deploy vm from template
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars/vm_deploy_var.yml
    - include_vars: vault/admin_ag_pwd.yml
  tasks:
      - name: Clone the template
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          template: "{{ vm_template }}"
          datastore: nfs_datastore03
          datacenter: "{{ vcenter_datacenter }}"
          name: "{{ vm_name }}"
          folder: "{{ vcenter_destination_folder }}"
          annotation: please add annotation
          state: poweredon
